DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS customer;

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE customer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  cust_number INTEGER NOT NULL,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  postal_number TEXT NOT NULL,
  postal_address TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);